# Generated by Django 2.2.4 on 2019-09-07 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('title', models.CharField(max_length=100, verbose_name='文章名称')),
                ('author', models.CharField(max_length=50, verbose_name='文章作者')),
                ('body', models.TextField(verbose_name='文章内容（markdown，包括标题）')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读量')),
                ('message_count', models.IntegerField(default=0, verbose_name='留言数')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('visible_permission', models.SmallIntegerField(choices=[(1, '所有人可见'), (2, '登录用户可见'), (3, '创建者可见')], default=1, verbose_name='可见权限')),
                ('collect_name', models.CharField(max_length=50, unique=True, verbose_name='文集名称')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '文集',
                'verbose_name_plural': '文集',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('visible_permission', models.SmallIntegerField(choices=[(1, '所有人可见'), (2, '登录用户可见'), (3, '创建者可见')], default=1, verbose_name='可见权限')),
                ('label_name', models.CharField(max_length=50, unique=True, verbose_name='文章标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ('-create_time',),
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('nickname', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='用户邮箱')),
                ('message_body', models.TextField(verbose_name='留言内容')),
                ('is_reply', models.BooleanField(default=False, verbose_name='是否回复留言')),
                ('is_author', models.BooleanField(default=False, verbose_name='是否是作者留言')),
                ('article_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='留言对应文章')),
                ('reply_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Messages', verbose_name='回复留言的ID')),
            ],
            options={
                'verbose_name': '留言',
                'verbose_name_plural': '留言',
                'ordering': ('-create_time',),
            },
        ),
    ]
