# Generated by Django 2.2.4 on 2019-09-07 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labels',
            name='create_user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='collections',
            name='create_user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='创建用户'),
        ),
        migrations.AddField(
            model_name='articles',
            name='collection_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articles.Collections', verbose_name='文章集合'),
        ),
        migrations.AddField(
            model_name='articles',
            name='labels_all',
            field=models.ManyToManyField(related_name='relate_articles_labels', to='articles.Labels', verbose_name='文章标签'),
        ),
    ]
