# Generated by Django 2.2.4 on 2019-09-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190907_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collections',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='collections',
            name='visible_permission',
            field=models.SmallIntegerField(choices=[(1, '所有人可见'), (2, '普通用户可见'), (3, '仅自己可见')], default=1, verbose_name='可见权限'),
        ),
        migrations.AlterField(
            model_name='labels',
            name='visible_permission',
            field=models.SmallIntegerField(choices=[(1, '所有人可见'), (2, '普通用户可见'), (3, '仅自己可见')], default=1, verbose_name='可见权限'),
        ),
    ]
