# Generated by Django 2.2.4 on 2019-09-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190916_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='message_count',
        ),
        migrations.AddField(
            model_name='articles',
            name='collection_order',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='文集顺序'),
        ),
        migrations.AddField(
            model_name='collections',
            name='read_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='阅读量'),
        ),
    ]
