# Generated by Django 2.2.4 on 2019-09-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190918_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='reply_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='回复留言的用户昵称'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='reply_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Messages', verbose_name='回复留言楼主的ID'),
        ),
    ]
