# Generated by Django 2.2.4 on 2019-10-02 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_url',
            new_name='image_info',
        ),
    ]
